# Generated by Django 5.0.10 on 2025-01-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudcix_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apilog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
