# Generated by Django 2.0.7 on 2018-07-09 13:50
from typing import List
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies: List[str] = []

    operations = [
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.CharField(max_length=64)),
                ('api_key', models.CharField(max_length=64)),
                ('url', models.URLField()),
                ('method', models.CharField(max_length=10)),
            ],
        ),
    ]
